_target_: langchain_huggingface.ChatHuggingFace
llm:
  _target_: langchain_huggingface.HuggingFacePipeline.from_model_id
  model_id: meta-llama/Llama-3.2-3B-Instruct
  task: text-generation
  device_map: auto
  pipeline_kwargs:
    temperature: ${oc.select:temperature, 0.6}
    max_new_tokens: 512
    return_full_text: false
