version: 1
disable_existing_loggers: false

formatters:
  simple:
    format: "[%(levelname)s]: %(message)s"
  file-simple:
    format : "%(asctime)s - %(name)s - [%(levelname)s]: %(message)s"
  error-simple:
    format: "[STDERR: %(levelname)s %(asctime)s %(filename)s:%(lineno)d]"

handlers:
  stdout:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
  # file:
  #   class: logging.FileHandler
  #   level: DEBUG
  #   formatter: file-simple
  #   filename: src/persuasion_bias/logs/session.log
  #   mode: a
  stderr:
    class: logging.StreamHandler
    level: ERROR
    formatter: error-simple
    stream: ext://sys.stderr

loggers:
  persuasion_bias:
    level: WARNING
    propagate: yes

root:
  level: DEBUG
  handlers:
    - stdout
    - stderr
    # - file